[build]
  command   = "npm run build"
  publish   = "dist/static"
  functions = "functions"

[context.production.environment]
  NODE_VERSION = "18.17.1"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
